[package]
name = "chip8-rust"
authors = ["Ensar Emir EROL"]
version = "0.1.0"
edition = "2021"

[dependencies]
beep = "0.3.0"
clap = { version = "4.5.20", features = ["derive"] }
crossterm = "0.28.1"
rand = "0.8.5"

